#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: odd hidestars indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{hidelinks}
#+LaTeX_CLASS_OPTIONS: [letterpaper]

{{{HEADER}}}

* Experience
*** Recurser at the Recurse Center
***** Jun - Aug, 2014
Recurse Center is a collaborative, self-directed, 12-week programming retreat. I
spent my time getting more familiar with functional programming, the internals
of Python, and building things using embedded hardware.

*** Software Developer at Enthought
***** Sep 2011 - May 2014
Helped build a Qt (PySide) based development environment for
Scientists/Engineers.  Also helped develop the initial design and build the
first cut of an application deployment platform for Python based apps.  Gained
some taste for good design, while working here.

*** Research Associate at [[http://fossee.in][FOSSEE]], IIT Bombay
***** Jul 2009 - Jul 2011
Designed and developed material & helped conduct workshops to train college
level teachers and students in using Python for Scientific Computing.

*** Intern at STMicroelectronics
***** Jan - Jun, 2009
Developed a new sub-system for automated testing of a few of the processes, for
testing the software on a DigitalTV Chip.  This system would, in future,
improve the amount of automation in the testing process.

*** Intern at National Physical Labs
***** May - Jul, 2007
Helped in the fabrication and optical & mechanical characterization of
transparent nano-structured $Zn_{1-x}Mn_xO$ thin films.
* Projects
*** cinspect
~cinspect~ is an attempt to provide ~inspect~-like inspection for Python's
built-ins and extension modules written in C.  I built a tool to generate
indexes from the C sources of Python (or an extension module) using ~libclang~,
which can later be queried using an ~inspect~-like API.
*** LEDBot
A bot that receives messages with text and images, and displays them on a
LED screen.  Helped improve design of the code for extensibility and
improved performance while on embedded hardware.
*** crumb
A disqus-like commenting system that (ab)uses GitHub issues as the
"database". It is an experimental hack, but can be used on real sites if
the users are all expected to have GitHub accounts.

*** org2blog
An ~Emacs~ minor mode for blogging from ~org-mode~ to Wordpress that
makes publishing and managing blog posts extremely easy, and hence loved
by many users.
* Education
*** BITS Pilani, Goa Campus, India
***** Aug 2005 - Jun 2009
/B.E.(Hons.), Electrical and Electronics/, GPA: 8.31/10
* Skills
  - Most comfortable with :: Python, Javascript, Emacs Lisp, HTML/CSS, Git, Linux
  - Have worked with :: Go, C, R, Octave, Haskell, Bash, LaTeX, Mercurial
