#+OPTIONS: toc:nil H:10
#+LATEX_HEADER: \def \email {eliotbaker@gmail.com}
#+LATEX_HEADER: \def \phone {215.740.1960}
#+LATEX_HEADER: \def \url {http://eliotbaker.com}
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_CLASS_OPTIONS: [10pt]

#+TITLE: ELIOT BAKER

* Objective
** /Present/
   To contribute to an agile team as a software engineer focusing on
   development of mobile web applications utilizing the latest HTML5,
   CSS3, and JavaScript libraries and frameworks.
* Experience
** December 2013 -- November 2014
   *Software Engineer*, [[http://lessthan3.com][LessThan3]], San Francisco, CA
   - Developed features for multiple products in full-stack coffeescript environment. 
   - Created admin dashboard tools for a live-event CMS used by Ultra Music Festival, EDC, HARD Summer, and Insomniac among others.
   - Developed client-side interfaces using coffeescript, backbone, stylus, teacup, history api, and jQuery.
   - Helped build documentation and tutorials for future developers on the platform.
   - Built back-end interfaces using node.js, express, socket.io, coffeescript, mongodb, and other 3rd party APIs

** April 2013 -- November 2013
   *Web Application Consultant*, Philadelphia, PA
   - Designed client web interfaces using Twitter bootstrap along side HTML and CSS.
   - Developed web application functionilty with jQuery parsing JSON data.
   - Managed data to implement MVC paradigms in an agile development environment versioned by git.
   - Generated dynamic PDF documents with third party libraries parsing xml input data.
   - Created renderings of data sets in tables using DataTables as well as pie charts with HighCharts and jqPlot.

** November 2011 -- April 2013
   *Software Engineer*, [[http://colorquick.com][ColorQuick]], Pennsauken, NJ
   - Developed web interfaces in HTML/CSS using Twitter bootstrap
     along side JavaScript and jQuery.
   - Adopted REST API paradigm for interfacing in real time with legacy applications over HTTP.
   - Managed servers running mySQL, nginx, and git on CentOS Linux.

** May 2009 -- November 2011
   *Independent Contractor*, New Orleans, LA
   - Installed systems for Dell and HP for a variety of client sites and site sizes.
   - Configured medium sized wired and wireless LANs with a strong understanding of TCP/IP.

** May 2008 -- August 2008
   *Technician Senior Assistant (Co-op)*, [[http://csc.com][Computer Science Corporation]], Marlton, NJ
   - Applied computer science principles to automate business processes.
   - Automated ticket retrieval and updates to increase efficiency by over 300%.

** May 2007 -- August 2007
   *Software Engineer Co-op*, [[http://ibm.com ][IBM]], West Chester, PA
   - Developed Java webapp using IBM API to keep a local site record of employee information.
* Education
** 2005 -- 2009
   *B.S. Computer Engineering*, Pennsylvania State University, Cumulative GPA: 3.2/4.0

* Skills & Technology
** Languages
   |  *Javascript* | *CoffeeScript* | *HTML5* | *CSS3* | *Python* | PHP | C/C++ | Objective-C | Erlang |
*** Framworks
    | *express* | *stylus* | *teacup* | *backbone.js* | socket.io | Twitter Bootstrap| Flask (python)|
*** Libraries
    | *jQuery* | *underscore* | jquery-cycle2 | MixItUp | jquery-fancybox | fontello | chosen |
*** Data
    | *MySQL* | *MongoDB* | redis | SQLite | JSON | 
*** Servers
    | *Linux(Debian)* | Linux(CentOS) | FreeBSD | nginx | node.js |
*** Methodology
    | *REST* | *MVC* | AJAX | SOAP |
*** Tools
    | *vim* | *git* | *npm* | *bower* | *grunt* | emacs | mercurial |


* Activities
** 2013 -- Present
   *JavaScript Developers Meetup*
** 2013 -- Present
   *Node.js Meetup*
** 2012
   *[[https://github.com/gcs272/Pots-Pans][Pots-N-Pans]]*, Hack the Change, Second Place
   - An sms based alerting system for developing nations location based subscription.
