#+OPTIONS: toc:nil H:10
#+STARTUP: odd hidestars
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+TITLE: {{{FULL}}}

* Experience
*** TODO Jun 2014 - Aug 2014
    *Hacker School*, Student
*** Sep 2011 - May 2014
    *Enthought*, Software Developer

    Worked on building a Qt (PySide) based development environment for
    Scientists and Engineers.  Also helped in the initial stages of building an
    application deployment platform for Python based apps.  Gained some taste
    for good design and software engineering, while doing this.

*** Jul 2009 - Jul 2011
    *[[http://fossee.in][FOSSEE]], IIT Bombay*, Research Associate

    Designed and developed material & helped conduct workshops to train college
    level teachers and students in using Python for Scientific Computing.

*** Jan - Jun, 2009
    *STMicroelectronics*, Intern

    Developed a new sub-system for automated testing of a few of the processes,
    for testing the software on a DigitalTV Chip.  This system would, in
    future, improve the amount of automation in the testing process.

*** May - Jul 2007
    *NPL*, Intern

    Helped fabrication and optical & mechanical characterization of transparent
    nano-structured $Zn_{1-x}Mn_xO$ thin films.
* TODO Projects
* Education
*** 2005 - 2009
    *B.E.(Hons.), Electrical and Electronics*
***** Institution
      Birla Institute of Technology and Science - Pilani, Goa Campus
***** CGPA
      8.31/10
* Technical Skills
*** Languages & Libraries
    - Most comfortable with :: Python, Javascript, Emacs Lisp, HTML/CSS, Git, Linux
    - Have worked with :: C, R, Octave, Haskell, Mercurial, Bash
